// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HeaderMenuController from "./header_menu_controller"
application.register("header-menu", HeaderMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StaffConditionController from "./staff_condition_controller"
application.register("staff-condition", StaffConditionController)

import TaskFieldsController from "./task_fields_controller"
application.register("task-fields", TaskFieldsController)

import TaskFormController from "./task_form_controller"
application.register("task-form", TaskFormController)

import TypewriterFixedController from "./typewriter_fixed_controller"
application.register("typewriter-fixed", TypewriterFixedController)
