ARG RUBY_VERSION=3.2.10
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  pkg-config \
  libpq-dev \
  libyaml-dev \
  curl \
  && rm -rf /var/lib/apt/lists/*

ENV RAILS_ENV=development \
  BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
