ARG RUBY_VERSION=3.2.10
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  pkg-config \
  libpq-dev \
  libyaml-dev \
  curl \
  cron \
  postgresql-client \
  libvips \
  && rm -rf /var/lib/apt/lists/*

ENV RAILS_ENV=development \
  BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

# cronログ用ディレクトリとファイルの作成
RUN mkdir -p /rails/log && \
  touch /rails/log/cron.log && \
  chmod 777 /rails/log && \
  chmod 666 /rails/log/cron.log

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
